spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/mahjong_db}
    username: ${DATABASE_USERNAME:mahjong_user}
    password: ${DATABASE_PASSWORD:mahjong_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: co.jp.ulsystems.mahjong.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    co.jp.ulsystems.mahjong: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
